### ISSUE TITLE
DIYMALL doesn't work

### ISSUE THREAD

**Issue by yoandresmza** [nayarsystems/nearkey#2]
Hi, I flashed virkey on my DIYMALL REALY32 but after that board seems like dead.
And not only that, now I can't re-flash again or roll back to the original version.
When I try to flash with ESP DOWNLOAD TOOL I receive the messages:
- Chip sync error: Failed to connect to ESP32: Timed out waiting for packet header
- ESP32 Chip sync error esp_sync_blocking

It seems like the ESP32 doesn't go into flashing mode.

Any help?

**Comment by soyangel** [comment]
Flashing a firmware shouldn't damage the board like that.

Please check your USB-serial TTL is 3.3 v, if you were using a 5v one you can damage your board.

**Comment by yoandresmza** [comment]
Hi Soyangel, tanks for the answer.
I finally got my board to work. Apparently, the pull up resistor on the EN pin burned, just I replaced it and everything goes smooth again.
